### ISSUE TITLE
Построить диаграмму классов ИС для ранее нормализованной БД, в соответствии с SOLID

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Saratov_Sergei#1]
Студент(ка): Саратов Сергей Сергеевич
Выполнить до 16.10.2020 18:00

**Comment by TheHalione** [comment]
![Построить диаграмму классов ИС для ранее нормализованной БД, в соответствии с SOLID](https://user-images.githubusercontent.com/73168783/98572627-e5405680-22c6-11eb-847c-33219ce5f2ab.png)

**Comment by bespalova-m-a** [comment]
Работа принята
