### ISSUE TITLE
Создать скетч GUI ПП под ранее созданную БД (магазин канцтоваров). Выполнить до 23.10.2020 18:00

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Saratov_Sergei#2]
Студент(ка): Саратов Сергей Сергеевич

**Comment by TheHalione** [comment]
![Создать скетч GUI ПП под ранее созданную БД (магазин канцтоваров)](https://user-images.githubusercontent.com/73168783/98568263-f5a20280-22c1-11eb-9892-b0c48b21aed7.png)

**Comment by bespalova-m-a** [comment]
Работа принята
